name: Test
on: 
  pull_request:
    branches:
      - yslen7-patch-1
jobs:
  build:
    if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.GITHUB_TOKEN}}       
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Push changes
        run: |
          git config --global user.name 'yslen7'
          git config --global user.email 'yslen7@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/yslen7/TestAWS.git
          git remote update
          git fetch --all
      - name: Get branches
        id: branchlist
        run: echo "::set-output name=branchlist::$(git branch -a)"
      - name: Print branch
        run: echo "${{ steps.branchlist.outputs.branchlist}} "
      - name: Get current branch
        id: branch
        run: echo "::set-output name=branch::$(git branch)"
      - name: Push main
        run: |
          git remote update
          git fetch --all
          git checkout main
          git merge origin/yslen7-patch-1
          git push --set-upstream origin main
          
