name: Test
on: 
  pull_request:
    branches:
      - yslen7-patch-1
jobs:
  build:
    #if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.GITHUB_TOKEN}}         
      - name: Push changes
        run: |
          git push origin main
          
